### ISSUE TITLE
Make fails with error: use of undeclared identifier 'ImGuiKey_KeyPadEnter'

### ISSUE THREAD

**Issue by dsego** [pthom/rpn_calculator#1]
```sh
make -j 4
[  2%] Built target glad
[  4%] Built target stb_hello_imgui
[ 16%] Built target plutovg
[ 20%] Built target plutosvg
[ 20%] Built target smiley
[ 28%] Built target imgui
[ 97%] Built target hello_imgui
Copying OS X content rpn_calculator.app/Contents/Resources/icon.icns
[ 98%] Building CXX object CMakeFiles/rpn_calculator.dir/rpn_calculator_app.cpp.o
/Users/davorin/Code/rpn_calculator/rpn_calculator_app.cpp:348:68: error: use of undeclared identifier 'ImGuiKey_KeyPadEnter'; did you mean 'ImGuiKey_KeypadEnter'?
  348 |     if (ImGui::IsKeyPressed(ImGuiKey_Enter) || ImGui::IsKeyPressed(ImGuiKey_KeyPadEnter))
      |                                                                    ^~~~~~~~~~~~~~~~~~~~
      |                                                                    ImGuiKey_KeypadEnter
/Users/davorin/Code/rpn_calculator/build/_deps/hello_imgui-src/external/imgui/imgui.h:1539:5: note: 'ImGuiKey_KeypadEnter' declared here
 1539 |     ImGuiKey_KeypadEnter,
      |     ^
1 error generated.
make[2]: *** [CMakeFiles/rpn_calculator.dir/rpn_calculator_app.cpp.o] Error 1
make[1]: *** [CMakeFiles/rpn_calculator.dir/all] Error 2
make: *** [all] Error 2

```

Updating `ImGuiKey_KeyPadEnter` to `ImGuiKey_KeypadEnter` in `rpn_calculator_app.cpp` (line 348) fixes the issue for me.
Could be related to Imgui change  here https://github.com/ocornut/imgui/pull/7143  .

**Comment by pthom** [comment]
Hello
Thank you! you probably found the reason for the issue.
Could you test the fix on your side, and if it works, could you also propose a PR which solves the issue here ?
Thanks

**Comment by dsego** [comment]
Ok, this seems to be the actual change
https://github.com/ocornut/imgui/pull/2625

Specifically this commit
https://github.com/ocornut/imgui/commit/afffcd5810d030e24056c1a61f27a6eb632f50ed

> Inputs: rename ImGuiKey_KeyPadEnter > ImGuiKey_KeypadEnter (https://github.com/ocornut/imgui/pull/2625)

This is the version pulled in `rpn_calculator/build/_deps/hello_imgui-src/external/imgui`
**dear imgui, v1.91.5**


And this method was renamed in dear imgui  v1.90.1
https://github.com/ocornut/imgui/releases/tag/v1.90.1


PR for review
https://github.com/pthom/rpn_calculator/pull/2

**Comment by pthom** [comment]
Thanks a lot, I merged your PR!
